modLoader="javafml" 
loaderVersion="[31,)" # This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="http://github.com/prodzpod/%MODID%/issues/"
showAsResourcePack=false

[[mods]] 
modId="%MODID%" 
version="%VERSION%" 
displayName="%MODNAME%" 
# updateJSONURL="http://myurl.me/" 
displayURL="http://prodzpod.o-r.kr:8080/mods/%MODID%"
logoFile="%MODID%.png"
credits="\n    §dVazkii§7 for §fP§bs§9i\n    §9Kamefrede§7 for §fR§aa§2ndom §fP§bS§9I§1deas\n    §6Wiiv§7, §eWireSegal§7, §9Kamefrede§7, §cWillewillus§7 for co-authoring Psi"
authors="§c§op§6§or§e§oo§a§od§b§oz§9§op§5§oo§d§od" 
description='''A general expansion add-on for §bPsi §rand §9Random PSIdeas§7(for now, adds some of the functionalities rPSIdeas have) §7(also some other psi addons and other mods)§r.'''

[[dependencies.%MODID%]]
    modId = "forge"
    mandatory = true
    versionRange = "[24,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.%MODID%]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.13,]"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.%MODID%]]
    modId = "patchouli"
    mandatory = true
    versionRange = "[1.15.2-1.2-27,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.%MODID%]]
    modId = "psi"
    mandatory = true
    versionRange = "[r1.2-82,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.%MODID%]]
    modId = "jei"
    mandatory = false
    versionRange = "[6.0.0,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.%MODID%]]
    modId = "psipherals"
    mandatory = false
    versionRange = "[1.3,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.%MODID%]]
    modId = "curios"
    mandatory = false
    versionRange = "[2.0,)"
    ordering = "AFTER"
    side = "BOTH"
